CREATE DATABASE mimomesmo_db;                 /*JÁ------*/

USE mimomesmo_db;                             /*JÁ------*/ 

CREATE TABLE CATEGORIA_PROD(
	IDCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(15) NOT NULL UNIQUE,
	OBSERVACAO TINYTEXT,
	FOTO BLOB
);                                            /*JÁ------*/

INSERT INTO CATEGORIA_PROD (IDCATEGORIA, NOME, OBSERVACAO, FOTO) VALUES (NULL, 'RAÇÃO', 'INDEPENDENTE DO TIPO. ARMAZENAR SEMPRE POR KILO', NULL);
INSERT INTO CATEGORIA_PROD (IDCATEGORIA, NOME, OBSERVACAO, FOTO) VALUES (NULL, 'ACESSÓRIOS', 'CAIXAS DE TRANSPORTE, SANITÁRIO CANINO, COLEIRAS, ETC', NULL);
INSERT INTO CATEGORIA_PROD (IDCATEGORIA, NOME, OBSERVACAO, FOTO) VALUES (NULL, 'BRINQUEDOS', 'NÃO ADICIONAR BRINQUEDOS NA CATEGORIA ACESSÓRIOS', NULL);
INSERT INTO CATEGORIA_PROD (IDCATEGORIA, NOME, OBSERVACAO, FOTO) VALUES (NULL, 'HIGIENE', 'PRODUTOS DE USO CONTÍNUO. SHAMPOO, PERFUME, AREIA HIGIÊNICA, TAPEDE, ETC. NÃO ARMAZENAR SANITÁRIO CANINO E OUTROS ITENS DURAVEIS', NULL);
INSERT INTO CATEGORIA_PROD (IDCATEGORIA, NOME, OBSERVACAO, FOTO) VALUES (NULL, 'MEDICAMENTOS', 'ARMAZENAR MEDICAMENTOS. BRAVECTO, SCALIBUR SÃO INSETICIDAS!', NULL);
INSERT INTO CATEGORIA_PROD (IDCATEGORIA, NOME, OBSERVACAO, FOTO) VALUES (NULL, 'VENENOS E INSET', 'TUDO PARA CONTROLE DE PRAGAS, INCLUSIVE ACESSÓRIOS DO GÊNERO, COMO ADESIVO PARA RATO', NULL);
                                              /*JÁ------*/

/*JÁ------*/
CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	CODIGO VARCHAR(10),
	COD_BARRAS CHAR(13),
	DESCRICAO VARCHAR(64) NOT NULL UNIQUE,
	OBSERVACAO TINYTEXT,
	FOTO BLOB,
	ESTOQUE_ATUAL INT NOT NULL, /*TEM QUE HAVER UM GATILHO ORIUNDO DE  [FORNECIMENTO] E OUTRO DE [PRODUTOSVENDA]*/
	ESTOQUE_MINIMO INT NOT NULL, /*PARA MOSTAR ALERTAS DE ESTOQUE BAIXO*/
	
	ID_CATEGORIA INT,
	FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA_PROD(IDCATEGORIA)	
);/*JÁ------*/

INSERT INTO PRODUTO VALUES (NULL, NULL,'7898416700491', 'BIOTRIL VERMÍFUGO', NULL, NULL, 3, 1, 6);

CREATE TABLE FORNECEDOR(
	IDFORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
	PESSOA ENUM('FISICA','JURIDICA') NOT NULL,
	CPF_CNPJ VARCHAR(18) NOT NULL UNIQUE,
	RAZAO_SOCIAL VARCHAR(64) NOT NULL,
	FANTASIA VARCHAR(64)
);/*JÁ------*/

INSERT INTO FORNECEDOR (IDFORNECEDOR, PESSOA, CPF_CNPJ, RAZAO_SOCIAL, FANTASIA)
VALUES (NULL, "JURIDICA", "00.820.127/0001-57", "PRESTIGIO LOGISTICA LTDA", "PRESTIGIO");
INSERT INTO FORNECEDOR (IDFORNECEDOR, PESSOA, CPF_CNPJ, RAZAO_SOCIAL, FANTASIA)
VALUES (NULL, "JURIDICA", "02.275.901/0001-11", "Cda Central De Distribuicao Azevedo Ltda", "CDA");
INSERT INTO FORNECEDOR (IDFORNECEDOR, PESSOA, CPF_CNPJ, RAZAO_SOCIAL, FANTASIA)
VALUES (NULL, "JURIDICA", "10.314.122/0001-06", "Petmais Distribuidora e Servicos Veterinarios LTDA", "Petmais Distribuidora");

CREATE TABLE EMAILFORNECEDOR(
	IDEMAILFORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
	EMAIL VARCHAR(64) UNIQUE,
	OBSERVACAO TINYTEXT,
	
	ID_FORNECEDOR INT,
	FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR)
);/*JÁ------*/

CREATE TABLE TELEFONEFORNECEDOR(
	IDTELEFONEFORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
	DDD CHAR(2) NOT NULL,
	NUMERO VARCHAR(11) NOT NULL,
	OBSERVACAO TINYTEXT,
	
	ID_FORNECEDOR INT,
	FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR)
);/*JÁ------*/

CREATE TABLE ENDERECOFORNECEDOR(
	IDENDERECOFORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
	LOGRADOURO VARCHAR (50) NOT NULL,
	NUMERO INT,
	CEP CHAR(10) NOT NULL,
	BAIRRO VARCHAR(32) NOT NULL,
	CIDADE VARCHAR (32) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	COMPLEMENTO VARCHAR(15),
	REFERENCIA VARCHAR(100),
	
	ID_FORNECEDOR INT,
	FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR)
);/*JÁ------*/

CREATE TABLE FORNECIMENTO(
	IDFORNECIMENTO INT PRIMARY KEY AUTO_INCREMENT,
	DATAENTRADA DATE NOT NULL,
	VALORUNITARIO FLOAT NOT NULL,
	QUANTIDADE INT NOT NULL,
	COMNOTA ENUM('SIM','NAO') NOT NULL,
	
	ID_FORNECEDOR INT,
	ID_PRODUTO INT,
	FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR),
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);/*JÁ------*/
ALTER TABLE FORNECIMENTO CHANGE COLUMN DATAENTRADA DATAENTRADA DATETIME;

CREATE TABLE VENDEDOR(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	MATRICULA INT,
	NOME VARCHAR(64) NOT NULL,
	CPF VARCHAR(18) NOT NULL 
);/*JÁ------*/
INSERT INTO VENDEDOR VALUES(NULL, 20200001, 'ALBERTO', '054.658.147-32');
INSERT INTO VENDEDOR VALUES(NULL, 20200002, 'Naylma', '083.488.333-47');

CREATE TABLE ENDERECOCLIENTE(
	IDENDERECOCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	LOGRADOURO VARCHAR (50) NOT NULL,
	NUMERO INT,
	CEP CHAR(10) NOT NULL,
	BAIRRO VARCHAR(32) NOT NULL,
	CIDADE VARCHAR (32) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	COMPLEMENTO VARCHAR(15),
	REFERENCIA VARCHAR(100)
); /*JÁ------*/
INSERT INTO ENDERECOCLIENTE VALUES(NULL, 'Logradouro não declarado', NULL, '00.000-000', 'Bairro não declarado', 'Cidade não declarada','00',NULL,NULL);


CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (64) NOT NULL,
	EMAIL VARCHAR (64),
	INSTAGRAM VARCHAR (30),
	DATANASCIMENTO DATE,
	CELULAR VARCHAR(11),
	GENERO ENUM ('M', 'F'),
	
	ID_ENDERECOCLIENTE INT,
	FOREIGN KEY (ID_ENDERECOCLIENTE) REFERENCES ENDERECOCLIENTE (IDENDERECOCLIENTE)
); /*JÁ------*/
INSERT INTO CLIENTE VALUES (NULL, 'JOSEANE', NULL, NULL, NULL, NULL, 'F', 1);

CREATE TABLE PET(
	IDPET INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	TIPO ENUM('AVE', 'CÃO', 'COELHO', 'GATO', 'PEIXE','ROEDOR', 'RÉPTIL') NOT NULL,
	RACA VARCHAR (30),
	SEXO ENUM('M', 'F') NOT NULL,
	PORTE ENUM ('PP', 'MP', 'GP') NOT NULL,
	PESO FLOAT,
	DATANASCIMENTO DATE,
	
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
); /*JÁ------*/

CREATE TABLE VENDA(
	IDVENDA INT PRIMARY KEY AUTO_INCREMENT,
	DATAHORA DATE NOT NULL,
	
	ID_VENDEDOR INT,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(IDVENDEDOR),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
); /*JÁ------*/
INSERT INTO VENDA VALUES (NULL, NOW(), 1, 1);
ALTER TABLE VENDA CHANGE COLUMN DATAHORA DATAHORA DATETIME;
UPDATE VENDA SET DATAHORA= NOW() WHERE IDVENDA=1; 


CREATE TABLE PAGAMENTO(
	IDPAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
	QTDPARCELAS INT NOT NULL,
	FORMA ENUM('ESPÉCIE', 'TRANSFERÊNCIA', 'DÉBITO', 'CRÉDITO', 'BOLETO', 'FIADO') NOT NULL,
	VALOR FLOAT NOT NULL,
	CUSTOOPERACIONAL FLOAT NOT NULL,
	
	ID_VENDA INT,
	FOREIGN KEY (ID_VENDA) REFERENCES VENDA (IDVENDA) 
); /*JÁ------*/

CREATE TABLE PRODUTOSVENDA(
	QTDPRODUTO INT NOT NULL,
	VALOR FLOAT NOT NULL,
	LUCRO FLOAT NOT NULL,
	
	ID_VENDA INT,
	ID_PRODUTO INT,
	FOREIGN KEY (ID_VENDA) REFERENCES VENDA(IDVENDA),
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO),
	CONSTRAINT PKPRODUTOSVENDA PRIMARY KEY (ID_VENDA, ID_PRODUTO)
);/*JÁ------*/
INSERT INTO PRODUTOSVENDA VALUES(2, 25.00, 9.89, 1, 1);

/*-TRIGGERS-*/

DELIMITER $

CREATE TRIGGER PRODUTOSVENDA_INSERT
AFTER INSERT ON PRODUTOSVENDA
FOR EACH ROW
BEGIN
   UPDATE PRODUTO SET ESTOQUE_ATUAL= ESTOQUE_ATUAL - NEW.QTDPRODUTO
   WHERE IDPRODUTO = NEW.ID_PRODUTO;	
END$/*JÁ------*/



CREATE TRIGGER PRODUTOSVENDA_DELETE
AFTER DELETE ON PRODUTOSVENDA
FOR EACH ROW
BEGIN
   UPDATE PRODUTO SET ESTOQUE_ATUAL= ESTOQUE_ATUAL + OLD.QTDPRODUTO
   WHERE IDPRODUTO = OLD.ID_PRODUTO;	
END$/*JÁ------*/

DELIMITER ;
/*------------------*/ 
DELIMITER $
CREATE TRIGGER PRODUTOSVENDA_UPDATE
AFTER UPDATE ON PRODUTOSVENDA
FOR EACH ROW
BEGIN
	UPDATE PRODUTO SET ESTOQUE_ATUAL= ESTOQUE_ATUAL + OLD.QTDPRODUTO
	WHERE IDPRODUTO = OLD.ID_PRODUTO;
	UPDATE PRODUTO SET ESTOQUE_ATUAL= ESTOQUE_ATUAL - NEW.QTDPRODUTO
	WHERE IDPRODUTO = NEW.ID_PRODUTO;
END$   
DELIMITER ; /*--JÁ------*/

/*-FALTA AS TRIGGERS DE FORNECIMENTO.--*/
   
   
   
   